test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -20,13 +20,12 @@ jobs:
       - name: root
         uses: actions/checkout@v4
       - run: check.sh $(pwd) $(pwd)
+      - run: |
+          IFS=$'\n'
+          while read line; do echo "::error, line=substring=${line:7:5}::$line"; done < $FICHIER
       - name: norme
         run: |
-          if cat $FICHIER | wc -l > 0; then IFS=$'\n' while read line;
-          do
-          echo "::error, line=substring=${line:7:5}::$line"; done < $FICHIER
-          exit 1
-          fi
+          if cat $FICHIER | wc -l > 0; then exit 1; fi
 
   check_program_compilation:
     needs: check_coding_style
